<a href="https://colab.research.google.com/github/SeanMin00/DS_Bootcamp_NYU/blob/main/Week2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy Questions

1. Define two custom numpy arrays, say A and B. Generate two new numpyarrays by stacking A and B vertically and horizontally.

2. Find common elements between A and B. [Hint : Intersection of two sets]

3. Extract all numbers from A which are within a specific range. egbetween 5 and 10. [Hint: np.where() might be useful or boolean masks]

4. Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

Pandas Questions

5. From df filter the 'Manufacturer', 'Model' and 'Type' for every20th row starting from 1st (row 0).```df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')```

6. Replace missing values in Min.Price and Max.Price columns withtheir respective mean.```df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')```

7. How to get the rows of a dataframe with row sum > 100?```

df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
# 1. Define two custom numpy arrays, say A and B. Generate two new numpyarrays by stacking A and B vertically and horizontally.
A = np.array([1, 2, 3, 4, 5, 6])
B = np.array([4, 5, 6, 7, 8, 9])

Array1 = np.vstack((A, B))
print(Array1)
Array2 = np.hstack((A, B))
print(Array2)

[[1 2 3 4 5 6]
 [4 5 6 7 8 9]]
[1 2 3 4 5 6 4 5 6 7 8 9]


In [ ]:
# 2. Find common elements between A and B. [Hint : Intersection of two sets]
common_elements = np.intersect1d(A, B)
print(common_elements)


[4 5 6]


In [ ]:
# 3. Extract all numbers from A which are within a specific range. eg- between 5 and 10.
# [Hint: np.where() might be useful or boolean masks]
specific_range = np.where((A >= 5) & (A <= 10))
print(specific_range)

(array([4, 5]),)


In [ ]:
#4 Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

filtered_rows = iris_2d[(iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)]
print(filtered_rows)

[[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


In [ ]:
#5 From df filter the 'Manufacturer', 'Model' and 'Type' for every20th row starting from 1st (row 0).
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

selected_columns = df[['Manufacturer', 'Model', 'Type']].head(20)
print(selected_columns)

   Manufacturer       Model     Type
0         Acura     Integra    Small
1           NaN      Legend  Midsize
2          Audi          90  Compact
3          Audi         100  Midsize
4           BMW        535i  Midsize
5         Buick     Century  Midsize
6         Buick     LeSabre    Large
7         Buick  Roadmaster    Large
8         Buick     Riviera  Midsize
9      Cadillac     DeVille    Large
10     Cadillac     Seville  Midsize
11    Chevrolet    Cavalier  Compact
12    Chevrolet     Corsica  Compact
13    Chevrolet      Camaro   Sporty
14    Chevrolet      Lumina  Midsize
15    Chevrolet  Lumina_APV      Van
16    Chevrolet       Astro      Van
17    Chevrolet     Caprice    Large
18    Chevrolet    Corvette   Sporty
19          NaN    Concorde    Large


In [ ]:
#6 Replace missing values in Min.Price and Max.Price columns withtheir respective mean.
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
print(df[['Min.Price', 'Max.Price']])

mean_min_price = df['Min.Price'].mean()
mean_max_price = df['Max.Price'].mean()

df['Min.Price'].fillna(mean_min_price, inplace=True)
df['Max.Price'].fillna(mean_max_price, inplace=True)

print(df[['Min.Price', 'Max.Price']])

    Min.Price  Max.Price
0        12.9       18.8
1        29.2       38.7
2        25.9       32.3
3         NaN       44.6
4         NaN        NaN
..        ...        ...
88       16.6       22.7
89       17.6       22.4
90       22.9       23.7
91       21.8       23.5
92       24.8       28.5

[93 rows x 2 columns]
    Min.Price  Max.Price
0   12.900000  18.800000
1   29.200000  38.700000
2   25.900000  32.300000
3   17.118605  44.600000
4   17.118605  21.459091
..        ...        ...
88  16.600000  22.700000
89  17.600000  22.400000
90  22.900000  23.700000
91  21.800000  23.500000
92  24.800000  28.500000

[93 rows x 2 columns]


<ipython-input-30-d5072a6a3000>:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Min.Price'].fillna(mean_min_price, inplace=True)
<ipython-input-30-d5072a6a3000>:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try 

In [ ]:
#7 How to get the rows of a dataframe with row sum > 100?```
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))
print(df)
row_sum = df.sum(axis=1)
filtered_rows = df[row_sum > 100]
print(filtered_rows)

     0   1   2   3
0   32  30  15  18
1   23  29  38  14
2   30  14  26  37
3   36  24  15  10
4   34  17  21  22
5   25  37  13  35
6   29  21  22  14
7   17  39  28  25
8   30  23  32  24
9   11  17  32  15
10  16  11  22  35
11  15  14  27  39
12  23  19  36  21
13  35  11  34  14
14  27  24  31  38
     0   1   2   3
1   23  29  38  14
2   30  14  26  37
5   25  37  13  35
7   17  39  28  25
8   30  23  32  24
14  27  24  31  38
